### ISSUE TITLE
RNFileSystem is Undefined

### ISSUE THREAD

**Issue by herman-rogers** [hnq90/react-native-filesystem-v1#2]
At the moment using this package throws up an error that the const RNFileSystem = ReactNative.NativeModules.RNFileSystem in FileSystem.js is undefined. Thus none of the functions are working.

**Comment by hnq90** [comment]
Which version of React Native you are using?

**Comment by herman-rogers** [comment]
Sorry for the delay - busy times.

I'm working on "react-native": 0.48.4" at the moment.
